export enum NotificationType {
  SELECTION_WINDOW_OPEN = "SELECTION_WINDOW_OPEN",
  SELECTION_WINDOW_CLOSED = "SELECTION_WINDOW_CLOSED",
  MEAL_UNSELECTED_REMINDER = "MEAL_UNSELECTED_REMINDER",
  MEAL_SELECTED_CONFIRMATION = "MEAL_SELECTED_CONFIRMATION",
  MEAL_UNSELECTED_FINAL = "MEAL_UNSELECTED_FINAL",
  FEEDBACK_REPLY = "FEEDBACK_REPLY",
  FOOD_ARRIVED = "FOOD_ARRIVED",
}

export enum NotificationChannel {
  PUSH = "PUSH",
  EMAIL = "EMAIL",
  SMS = "SMS",
  WHATSAPP = "WHATSAPP",
}